---
title: "xG PL Table"
author: "Matthew Dzwil"
date: "1/16/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}
library("worldfootballR")
library("rlist")
library("gt")
library("tidyverse")
```

```{r}
#match_urls <- get_match_urls(country = "ENG", gender = "M", season_end_year = 2022)
match_summaries <- epl_results <- understat_league_match_results(league = "EPL", season_start_year = 2021)
```

```{r}
teams <- c("Arsenal","Aston Villa", "Brentford", "Brighton", "Burnley", "Chelsea","Crystal Palace","Everton","Leeds","Leicester","Liverpool","Manchester City","Manchester United","Newcastle United", "Norwich","Southampton","Tottenham","Watford","West Ham", "Wolverhampton Wanderers")
points <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)
```


```{r}

for(i in 1:nrow(match_summaries)) {
  if(match_summaries[i, ]$home_xG > (match_summaries[i, ]$away_xG +.4)){
    for(z in 1:length(teams)){
      if (teams[z]==match_summaries[i, ]$home_team){
         points[z]= points[z] + 3
      }
    }
  }
  else if(match_summaries[i, ]$away_xG > (match_summaries[i, ]$home_xG +.4)){
    for(z in 1:length(teams)){
      if (teams[z]==match_summaries[i, ]$away_team){
         points[z]= points[z] + 3
      }
    }
  }
  else{
    for(z in 1:length(teams)){
      if (teams[z]==match_summaries[i, ]$away_team){
         points[z]= points[z] + 1
      }
      else if(teams[z]==match_summaries[i, ]$home_team){
        points[z]= points[z] + 1
      }
    }
  }
}
  
```


```{r}
#folder <- "C:/Users/mattd/OneDrive/Documents/GitHub/PL21-22/GW22/logos" 
#file_list <- list.files(path=folder, pattern="*.png")
file_list <- c("C:/Users/mattd/OneDrive/Documents/GitHub/PL21-22/GW22/logos/Arsenal.png","C:/Users/mattd/OneDrive/Documents/GitHub/PL21-22/GW22/logos/AstonVilla.png","C:/Users/mattd/OneDrive/Documents/GitHub/PL21-22/GW22/logos/Brentford.png","C:/Users/mattd/OneDrive/Documents/GitHub/PL21-22/GW22/logos/Brighton.png","C:/Users/mattd/OneDrive/Documents/GitHub/PL21-22/GW22/logos/Burnley.png","C:/Users/mattd/OneDrive/Documents/GitHub/PL21-22/GW22/logos/Chelsea.png","C:/Users/mattd/OneDrive/Documents/GitHub/PL21-22/GW22/logos/CrystalPalace.png","C:/Users/mattd/OneDrive/Documents/GitHub/PL21-22/GW22/logos/Everton.png","C:/Users/mattd/OneDrive/Documents/GitHub/PL21-22/GW22/logos/Leeds.png","C:/Users/mattd/OneDrive/Documents/GitHub/PL21-22/GW22/logos/Leicester.png","C:/Users/mattd/OneDrive/Documents/GitHub/PL21-22/GW22/logos/Liverpool.png","C:/Users/mattd/OneDrive/Documents/GitHub/PL21-22/GW22/logos/ManchesterCity.png","C:/Users/mattd/OneDrive/Documents/GitHub/PL21-22/GW22/logos/ManchesterUnited.png","C:/Users/mattd/OneDrive/Documents/GitHub/PL21-22/GW22/logos/Newcastle.png","C:/Users/mattd/OneDrive/Documents/GitHub/PL21-22/GW22/logos/Norwich.png","C:/Users/mattd/OneDrive/Documents/GitHub/PL21-22/GW22/logos/Southampton.png","C:/Users/mattd/OneDrive/Documents/GitHub/PL21-22/GW22/logos/Tottenham.png","C:/Users/mattd/OneDrive/Documents/GitHub/PL21-22/GW22/logos/Watford.png","C:/Users/mattd/OneDrive/Documents/GitHub/PL21-22/GW22/logos/WestHam.png","C:/Users/mattd/OneDrive/Documents/GitHub/PL21-22/GW22/logos/Wolves.png")
```

```{r}
points_dif <- c(-3,1,7,-3,-3,1,11,1,0,-8,4,2,-5,0,-3,-2,-2,2,1,-4)
newTable <- data.frame(file_list,teams, points,points_dif,stringsAsFactors=FALSE)
PLtable <- newTable[order(-points),]
```


```{r}
PLtable %>%
  gt() %>%
  tab_header(title = "Premier League Table Based on xG",subtitle = "Up until GW22") %>%
  cols_label(
    file_list = "",
    teams = "Team",
    points = "xPoints",
    points_dif = "Points - xPoints") %>%
  tab_footnote(footnote = "If a team has 0.4 xG more than their opponent, this results in a win. Any teams within 0.4 xG of each other results in a draw.",locations = cells_column_labels(
      columns = points) )%>%
  tab_source_note(md("**Data:** Understat"))%>%
  tab_style(style = cell_text(color = "firebrick3"),
            locations = cells_body(columns = points_dif, rows = points_dif<0))%>%
  tab_style(style = cell_text(color = "forestgreen"),
            locations = cells_body(columns = points_dif, rows = points_dif>0))%>%
  text_transform(
    locations = cells_body(vars(file_list)),
    fn = function(file_list){
      lapply(file_list,local_image)
    })
  
  
```

